import "HV4D.idl";

namespace HV4D.HV4DWINRT
{
	enum HV4D_VOLUME_FILE_FIELD_ID {
		HV4D_ROOT			= 0,
		HV4D_DESMMDDYYYY	= 1,
		HV4D_DESHHMMSS		= 2,
		HV4D_DESSZ64		= 3,
		HV4D_DESNUM64		= 4,
		HV4D_SERMMDDYYYY	= 5,
		HV4D_SERHHMMSS		= 6,
		HV4D_SERSZ64		= 7,
		HV4D_SERNUM64		= 8,
		HV4D_RESERVE64		= 9,
		HV4D_COMMIT64		= 10,
		HV4D_FLAGS			= 11
	};

	struct HV4D_ENUMERATED_VOLUME_ENTRY {
		HV4D_VOLUME_FILE_FIELD_ID enumid;
		String value;
	};

}