import "HV4DWINRTCLASS.idl";
import "HV4DRENDER.idl";

namespace HV4D.HV4DWINRT
{
	struct HV4D_GFX_DESC {
		HV4D.HV4DWINRT.HV4D_RTCLASS_DESC	re;
		HV4D.HV4DRENDER.HV4DRESOLUTION		 r;
		HV4D.HV4DRENDER.HV4DAA				aa;
		HV4D.HV4DRENDER.HV4DMSAA			ms;
		HV4D.HV4DRENDER.HV4DSS				ss;
		HV4D.HV4DRENDER.HV4DFILTER			pm;
		HV4D.HV4DRENDER.HV4DPXFILTER		pf;
		HV4D.HV4DRENDER.HV4DGAMMA			 g;
		HV4D.HV4DRENDER.HV4DNEAR			np;
		HV4D.HV4DRENDER.HV4DFAR				fp;
	};

}