#include "pch.h"

#include "HV4DMapSystemFile.h"

using namespace winrt::HV4D;
using namespace winrt::HV4D::HV4DFLOW;
using namespace winrt::HV4D::HV4DWINRT;

namespace winrt::HV4D::HV4DDUALITY
{
	std::unordered_map<HV4D_SYSTEM_FILE_FIELD_ID, hstring> const tagHV4DMapSystemFileFieldIDToHstring{
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_GUID			,L"HV4D_GUID"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_MMM			,L"HV4D_MMM"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_MMDDYYYY		,L"HV4D_MMDDYYYY"		},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_HHMMSS		,L"HV4D_HHMMSS"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_NAME			,L"HV4D_NAME"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_PATH			,L"HV4D_PATH"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILE			,L"HV4D_FILE"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_OFFSET		,L"HV4D_OFFSET"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_SIZE			,L"HV4D_SIZE"			},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILEOFFSET	,L"HV4D_FILEOFFSET"		},
		{ HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILESIZE	    ,L"HV4D_FILESIZE"		} };

	const std::unordered_map<HV4D_SYSTEM_FILE_FIELD_ID, hstring>* const HV4DMapSystemFileFieldIDToHstring()
	{
		return &tagHV4DMapSystemFileFieldIDToHstring;

	}

	std::unordered_map<hstring, HV4D_SYSTEM_FILE_FIELD_ID> const tagHV4DMapSystemFileFieldHstringToID{
		{ L"HV4D_GUID"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_GUID			},
		{ L"HV4D_MMM"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_MMM			},
		{ L"HV4D_MMDDYYYY"		,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_MMDDYYYY		},
		{ L"HV4D_HHMMSS"		,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_HHMMSS			},
		{ L"HV4D_NAME"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_NAME			},
		{ L"HV4D_PATH"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_PATH			},
		{ L"HV4D_FILE"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILE			},
		{ L"HV4D_OFFSET"		,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_OFFSET			},
		{ L"HV4D_SIZE"			,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_SIZE			},
		{ L"HV4D_FILEOFFSET"	,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILEOFFSET		},
		{ L"HV4D_FILESIZE"	    ,HV4D_SYSTEM_FILE_FIELD_ID::HV4D_FILESIZE		} };

	const std::unordered_map<hstring, HV4D_SYSTEM_FILE_FIELD_ID>* const HV4DMapSystemFileFieldHstringToID()
	{
		return &tagHV4DMapSystemFileFieldHstringToID;

	}

}