import "HV4DWINRTCLASS.idl";

namespace HV4D.HV4DENUM
{
	enum HV4D_SYSTEM_MODULE_ID {
		HV4DCACHE		= 0,
		HV4DKERNEL		= 1,
		HV4DTREE		= 2,
		HV4DGLOBAL		= 3,
		HV4DWORLD		= 4,
		HV4DOBJECT		= 5,
		HV4DMETADATA	= 6
	};

	struct HV4D_ENUMERATED_SYSTEM_MODULE {
		HV4D_SYSTEM_MODULE_ID enumid;
		HV4D.HV4DWINRT.HV4D_RTCLASS_DESC rtclass;
	};

}