import "HV4DFLOW.idl";
import "HV4DRTCDESC.idl";

namespace HV4D.HV4DCONTRACT
{
	[uuid(C51B47BA-D6B9-4B5C-9571-9D1CC793CB1A)]
	[version(0x10000001)]
	interface IHV4DRTCDESCS : IInspectable
	{
		HV4D.HV4DFLOW.HV4DRETURN HV4DBlankRTCDESCS(HV4D.HV4DCONTRACT.IHV4DRTCDESC e);

		HV4D.HV4DFLOW.HV4DRETURN HV4DReadRTCDESCS(HV4D.HV4DCONTRACT.IHV4DRTCDESC e);

		HV4D.HV4DFLOW.HV4DRETURN HV4DWriteRTCDESCS(HV4D.HV4DCONTRACT.IHV4DRTCDESC e);

		HV4D.HV4DFLOW.HV4DRETURN HV4DValidateRTCDESCS();

		HV4D.HV4DFLOW.HV4DRETURN HV4DClearRTCDESCS();

	}

}