import "HV4DWINRTSYS.idl";

namespace HV4D.HV4DENUM
{
	enum HV4D_FILE_SYSTEM_ID {
		FHV4DDUALITY	= 0,
		FHV4D			= 1,
		FHV4DVOL		= 3,
		FHV4DBAT		= 2,
		FHV4DATT		= 4,
		FHV4DSFT		= 5
	};

	struct HV4D_ENUMERATED_FILE_SYSTEM {
		HV4D_FILE_SYSTEM_ID enumid;
		HV4D.HV4DWINRT.HV4D_SYSTEM_FILE_DESC file;
	};

}