import "HV4D.idl";

namespace HV4D.HV4DWINRT
{
	enum HV4D_RTCLASS_FIELD_ID {
		HV4D_HVID			= 0,
		HV4D_MMM			= 1,
		HV4D_NAME			= 2,
		HV4D_PATH			= 3,
		HV4D_DLL			= 4,
		HV4D_NAMESPACE		= 5,
		HV4D_CLASST			= 6
	};

	struct HV4D_ENUMERATED_RTCLASS_FIELD {
		HV4D_RTCLASS_FIELD_ID enumid;
		HV4D_RTCLASS_DESC field;
	};

}