import "HV4DWINRTCLASS.idl";

namespace HV4D.HV4DENUM
{
	enum HV4D_FILE_SYSTEM_MODULE_ID {
		HV4DBOOT		= 0,
		HV4DVOLUME		= 1,
		HV4DMOUNT		= 2,
		HV4DOSTREAM		= 3,
		HV4DISTREAM		= 4,
		HV4DBAT			= 5
	};

	struct HV4D_ENUMERATED_FILE_SYSTEM_MODULE {
		HV4D_FILE_SYSTEM_MODULE_ID enumid;
		HV4D.HV4DWINRT.HV4D_RTCLASS_DESC rtclass;
	};

}