namespace HV4D.HV4DWINRT
{
	enum HV4D_DUALITY_FIELD_ID {
		HV4D_PROJECT_HVID		= 0,
		HV4D_CREATED_MMDDYYYY	= 1,
		HV4D_CREATED_HHMMSS		= 2,
		HV4D_SAVED_MMDDYYYY		= 3,
		HV4D_SAVED_HHMMSS		= 4,
		HV4D_OPENED_MMDDYYYY	= 5,
		HV4D_OPENED_HHMMSS		= 6,
		HV4D_PROJECT_NAME		= 7,
		HV4D_INDEX_PATH			= 8,
		HV4D_INDEX_FILE			= 9,
		HV4D_PROJECT_PATH		= 10,
		HV4D_PROJECT_FILE		= 11
	};

	struct HV4D_ENUMERATED_DUALITY_ENTRY {
		HV4D_DUALITY_FIELD_ID enumid;
		String value;
	};

}