#include "pch.h"

#include "HV4DMapVolumeFile.h"

using namespace winrt::HV4D;
using namespace winrt::HV4D::HV4DFLOW;
using namespace winrt::HV4D::HV4DWINRT;

namespace winrt::HV4D::HV4DDUALITY
{
	std::unordered_map<HV4D_VOLUME_FILE_FIELD_ID, hstring> const tagHV4DMapVolumeFieldIDToHstring{
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_ROOT			,L"HV4D_ROOT"			},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESMMDDYYYY	,L"HV4D_DESMMDDYYYY"	},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESHHMMSS		,L"HV4D_DESHHMMSS"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESSZ64		,L"HV4D_DESSZ64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESNUM64		,L"HV4D_DESNUM64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERMMDDYYYY	,L"HV4D_SERMMDDYYYY"	},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERHHMMSS		,L"HV4D_SERHHMMSS"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERSZ64		,L"HV4D_SERSZ64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERNUM64		,L"HV4D_SERNUM64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_RESERVE64		,L"HV4D_RESERVE64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_COMMIT64	    ,L"HV4D_COMMIT64"		},
		{ HV4D_VOLUME_FILE_FIELD_ID::HV4D_FLAGS		    ,L"HV4D_FLAGS"			} };

	const std::unordered_map<HV4D_VOLUME_FILE_FIELD_ID, hstring>* const HV4DMapVolumeFieldIDToHstring()
	{
		return &tagHV4DMapVolumeFieldIDToHstring;

	}

	std::unordered_map<hstring, HV4D_VOLUME_FILE_FIELD_ID> const tagHV4DMapVolumeFieldHstringToID{
		{ L"HV4D_ROOT"			,HV4D_VOLUME_FILE_FIELD_ID::HV4D_ROOT			},
		{ L"HV4D_DESMMDDYYYY"	,HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESMMDDYYYY	},
		{ L"HV4D_DESHHMMSS"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESHHMMSS		},
		{ L"HV4D_DESSZ64"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESSZ64		},
		{ L"HV4D_DESNUM64"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_DESNUM64		},
		{ L"HV4D_SERMMDDYYYY"	,HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERMMDDYYYY	},
		{ L"HV4D_SERHHMMSS"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERHHMMSS		},
		{ L"HV4D_SERSZ64"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERSZ64		},
		{ L"HV4D_SERNUM64"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_SERNUM64		},
		{ L"HV4D_RESERVE64"		,HV4D_VOLUME_FILE_FIELD_ID::HV4D_RESERVE64		},
		{ L"HV4D_COMMIT64"	    ,HV4D_VOLUME_FILE_FIELD_ID::HV4D_COMMIT64		},
		{ L"HV4D_FLAGS"			,HV4D_VOLUME_FILE_FIELD_ID::HV4D_FLAGS			} };

	const std::unordered_map<hstring, HV4D_VOLUME_FILE_FIELD_ID>* const HV4DMapVolumeFieldHstringToID()
	{
		return &tagHV4DMapVolumeFieldHstringToID;

	}

}