import "HV4DOBJECT.idl";

namespace HV4DCONTRACT
{
    [uuid("28B6FC74-8DA1-4445-9DB6-72FBDABDA802")]
    [version(0x10000001)]
    interface IHV4DSESSION
    {



    }

    [default_interface]
    runtimeclass HV4DSESSION : [default] IHV4DOBJECT
    {
        HV4DSESSION();


    }

}
