import "HV4DWINRT.idl";

namespace HV4DCONTRACT
{ 
	[uuid("EDD4116A-DE20-46CB-9981-1FC04B44C86F")]
	[version(0x10000001)]
	interface IDocument
	{
		HV4D.HV4DRETURN HV4DBlankDocument(IWinRT e);

		HV4D.HV4DRETURN HV4DReadDocument(IWinRT e);

		HV4D.HV4DRETURN HV4DWriteDocument(IWinRT e);

		HV4D.HV4DRETURN HV4DValidateDocument();

		HV4D.HV4DRETURN HV4DClearDocument();

	}

    [default_interface]
    runtimeclass HV4DDOCUMENT
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DDOCUMENT();


    }

}
