namespace HV4DCONTRACT
{
    [uuid("CD7DFCE5-3208-424A-8498-3D96E011821A")]
    [version(0x10000001)]
    interface IHV4DOBJECT
    {



    }

    [default_interface]
    runtimeclass HV4DOBJECT : [default] IHV4DOBJECT
    {
        HV4DOBJECT();


    }

}
