import "HV4DFILE.idl";

namespace HV4DCONTRACT
{
	[uuid("F153E6F2-073F-4E5E-BE59-69285CD53B6E")]
	[version(0x10000001)]
	interface IHV4DTREE
	{
		HV4D.HV4DRETURN HV4DCurrentDir(out HV4DABI.HV4DKEY d);

		HV4D.HV4DRETURN HV4DDirTree(out HV4DABI.HV4DKEY[] d);

		HV4D.HV4DRETURN HV4DListFiles(out HV4DABI.HV4DKEY[] f);

		HV4D.HV4DRETURN HV4DDirChange(HV4DABI.HV4DKEY d);

		HV4D.HV4DRETURN HV4DMkDir(HV4DABI.HV4DKEY d);

		HV4D.HV4DRETURN HV4DDelDir(HV4DABI.HV4DKEY d);

		HV4D.HV4DRETURN HV4DCopyTree(HV4DABI.HV4DKEY p, HV4DABI.HV4DKEY q);

		HV4D.HV4DRETURN HV4DDelTree(HV4DABI.HV4DKEY d);

		HV4D.HV4DRETURN HV4DOpenFile(HV4DABI.HV4DKEY f, IFile l);

		HV4D.HV4DRETURN HV4DCloseFile(Boolean b, IFile e);

		HV4D.HV4DRETURN HV4DSaveFile(IFile e);

		HV4D.HV4DRETURN HV4DMoveFile(IFile e, HV4DABI.HV4DKEY q);

		HV4D.HV4DRETURN HV4DDelFile(IFile e);

		HV4D.HV4DRETURN HV4DVolumeSize(out UInt32 u, out UInt32 v, out UInt32 s);

	}

    [default_interface]
    runtimeclass HV4DTREE
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DTREE();


    }

}
