namespace HV4DCONTRACT
{
    [uuid("C54977AE-9E9C-4F43-A8CF-60075F49E7A9")]
    [version(0x10000001)]
    interface IClient
    {


    };

    [default_interface]
    runtimeclass HV4DCLIENT
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DCLIENT();


    }

}
