import "HV4DOBJECT.idl";

namespace HV4DCONTRACT
{
    [uuid("12887A64-4120-4220-AF51-781032B5C22E")]
    [version(0x10000001)]
    interface IHV4DFILE
    {



    }

    runtimeclass HV4DFILE : [default] IHV4DOBJECT
    {
        HV4DFILE();


    }

}
