namespace HV4DCONTRACT
{
	[uuid("782BFC8A-5017-4BB0-BE64-888F5F2CA27D")]
	[version(0x10000001)]
	interface IWinRT
	{
		 HV4D.HV4DRETURN HV4DValidateWINRT();

		 HV4D.HV4DRETURN HV4DClearWINRT();

	};

    [default_interface]
    runtimeclass HV4DWINRT
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DWINRT();


    }

}
