namespace HV4DCONTRACT
{
	[uuid("E5474E91-812D-4932-BA00-096B099CC92A")]
	[version(0x10000001)]
	interface IView
	{
		 HV4D.HV4DRETURN HV4DExpose();

	};

    [default_interface]
    runtimeclass HV4DTVIEW
        : HV4DT.IHV4DTNODE
    {
        HV4DTVIEW();

    }

}