#include "pch.h"
#include "HV4DMMDDYYYY.h"
#if __has_include("HV4DMMDDYYYY.g.cpp")
#include "HV4DMMDDYYYY.g.cpp"
#endif

using namespace winrt;

using namespace winrt::HV4D;

namespace winrt::HV4DABI::implementation
{
	HV4DMMDDYYYY::HV4DMMDDYYYY()
	{

		return;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DFromHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DFromABI(MMDDYYYY const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DFromWinRT(winrt::HV4DABI::HV4DMMDDYYYY const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DToHstring(hstring&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DToABI(MMDDYYYY&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DToWinRT(winrt::HV4DABI::HV4DMMDDYYYY)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DIsEqualHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DIsEqualABI(MMDDYYYY const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMMDDYYYY::HV4DIsEqualWinRT(winrt::HV4DABI::HV4DMMDDYYYY const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

}
