namespace HV4DCONTRACT
{
	[uuid("803EB33C-AE6A-4872-B067-F106F985681C")]
	[version(0x10000001)]
	interface IGlobal
	{
		 HV4D.HV4DRETURN HV4DPopulateFromFile();

	};

    [default_interface]
    runtimeclass HV4DGLOBAL
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DGLOBAL();


    }

}
