namespace HV4DABI
{
	struct NUMERIC {
		UInt8 b0;
		UInt8 b1;
		UInt8 b2;
		UInt8 b3;
		UInt8 b4;
		UInt8 b5;
		UInt8 b6;
		UInt8 b7;
	};

    [default_interface]
    runtimeclass HV4DNUMERIC
		: HV4DT.IHV4DTPROVIDER
    {
        HV4DNUMERIC();
    
		HV4D.HV4DRETURN HV4DFromUInt8(UInt8 e);

		HV4D.HV4DRETURN HV4DFromUInt16(UInt16 e);

		HV4D.HV4DRETURN HV4DFromUInt32(UInt32 e);

		HV4D.HV4DRETURN HV4DFromUInt64(UInt64 e);

		HV4D.HV4DRETURN HV4DFromHstring(String e);

		HV4D.HV4DRETURN HV4DFromABI(NUMERIC e);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DNUMERIC e);

		HV4D.HV4DRETURN HV4DToUInt8(out UInt8 e);

		HV4D.HV4DRETURN HV4DToUInt16(out UInt16 e);

		HV4D.HV4DRETURN HV4DToUInt32(out UInt32 e);

		HV4D.HV4DRETURN HV4DToUInt64(out UInt64 e);

		HV4D.HV4DRETURN HV4DToHstring(out String e);

		HV4D.HV4DRETURN HV4DToABI(out NUMERIC e);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DNUMERIC e);

		HV4D.HV4DRETURN HV4DIsEqualUInt8(UInt8 e);

		HV4D.HV4DRETURN HV4DIsEqualUInt16(UInt16 e);

		HV4D.HV4DRETURN HV4DIsEqualUInt32(UInt32 e);

		HV4D.HV4DRETURN HV4DIsEqualUInt64(UInt64 e);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String e);

		HV4D.HV4DRETURN HV4DIsEqualABI(NUMERIC e);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DNUMERIC e);


    }

}
