import "HV4DOBJECT.idl";
import "HV4DSESSION.idl";

namespace HV4DCONTRACT
{
    [uuid("93F0B4FD-4EBA-40D2-A112-8FBBF5B927E0")]
    [version(0x10000001)]
    interface IHV4DNODE
    {
        HV4D.IHV4DRETURN HV4DNodeSession(IHV4DSESSION e);

        HV4D.IHV4DRETURN HV4DNodeParent(IHV4DNODE n);

        HV4D.IHV4DRETURN HV4DNodeNextSibling(IHV4DNODE n);

        HV4D.IHV4DRETURN HV4DNodePrevSibling(IHV4DNODE n);

        HV4D.IHV4DRETURN HV4DNodeChildren(Windows.Foundation.Collections.IVector<IHV4DNODE> n);

    }

    runtimeclass HV4DNODE : [default] IHV4DOBJECT
    {
        HV4DNODE();


    }

}
