namespace HV4DABI
{
	struct MMDDYYYY {
		String mm;
		String dd;
		String yyyy;
	};

    [default_interface]
    runtimeclass HV4DMMDDYYYY
		: HV4DT.IHV4DTPROVIDER
    {
        HV4DMMDDYYYY();
    
		HV4D.HV4DRETURN HV4DFromHstring(String e);

		HV4D.HV4DRETURN HV4DFromABI(MMDDYYYY e);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DMMDDYYYY e);

		HV4D.HV4DRETURN HV4DToHstring(out String e);

		HV4D.HV4DRETURN HV4DToABI(out MMDDYYYY e);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DMMDDYYYY e);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String e);

		HV4D.HV4DRETURN HV4DIsEqualABI(MMDDYYYY e);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DMMDDYYYY e);

    }

}
