import "HV4DOBJECT.idl";

namespace HV4DCONTRACT
{
    [uuid("6312E9E2-3EFA-4C13-BA23-F6105B975982")]
    [version(0x10000001)]
    interface IHV4DSECTION
    {



    }

    runtimeclass HV4DSECTION : [default] IHV4DOBJECT
    {
        HV4DSECTION();


    }

}
