namespace HV4DCONTRACT
{
	[uuid("A4031738-0086-4F0D-A061-4E58B2D052E7")]
	[version(0x10000001)]
	interface IXML
	{
		 HV4D.HV4DRETURN HV4DUpdateDocumentFromXml();

		 HV4D.HV4DRETURN HV4DUpdateDocumentXml();

		 HV4D.HV4DRETURN HV4DCreateDocument();

		 HV4D.HV4DRETURN HV4DCloneDocument(HV4DABI.ABS f);

	}

    [default_interface]
    runtimeclass HV4DTXML
        : HV4DT.IHV4DTNODE
    {
        HV4DTXML();

    }

}