import "HV4DOBJECT.idl";

namespace HV4DCONTRACT
{
    [uuid("DDAE460F-CBE0-4503-97C4-37B049F5E6CA")]
    [version(0x10000001)]
    interface IHV4DDOCUMENT
    {



    }

    runtimeclass HV4DDOCUMENT : [default] IHV4DOBJECT
    {
        HV4DDOCUMENT();


    }

}
