SET search_path=hv4d_schema_public;
DROP TABLE IF EXISTS HV4D_TABLE_PROJECT_INDEX;
CREATE TABLE HV4D_TABLE_PROJECT_INDEX(
PROJECT_INDEX_HVID HV4D_TYPE_HVID PRIMARY KEY,
PROJECT_INDEX_MMM HV4D_TYPE_MMM NOT NULL,
PROJECT_INDEX_TAG HV4D_TYPE_MAXPATH NOT NULL ,
	UNIQUE(PROJECT_INDEX_TAG, PROJECT_INDEX_MMM),	
PROJECT_INDEX_PROFILE HV4D_TYPE_MAXPATH NOT NULL,
PROJECT_INDEX_WINDOW);