SET search_path=hv4d_schema_public;
DROP TABLE IF EXISTS HV4D_TABLE_PROJECT_INDEX;
CREATE TABLE HV4D_TABLE_PROJECT_INDEX(
PROJECT_INDEX_HVID HV4D_TYPE_HVID PRIMARY KEY,
PROJECT_INDEX_MMM HV4D_TYPE_MMM NOT NULL,
PROJECT_INDEX_TAG HV4D_TYPE_MAXPATH NOT NULL,
	UNIQUE(PROJECT_INDEX_TAG, PROJECT_INDEX_MMM),
PROJECT_INDEX_CREATED HV4D_TYPE_DATETIME NOT NULL,
PROJECT_INDEX_UPDATED HV4D_TYPE_DATETIME NOT NULL,
PROJECT_INDEX_DATABASE HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
PROJECT_INDEX_SCHEMA HV4D_TYPE_MAXPATH NOT NULL,
	UNIQUE(PROJECT_INDEX_DATABASE, PROJECT_INDEX_SCHEMA),
PROJECT_INDEX_ACCESS_LEVEL HV4D_TYPE_MAXPATH NOT NULL,
PROJECT_INDEX_ADMINISTRATOR_HVID HV4D_TYPE_HVID NOT NULL,
PROJECT_INDEX_ADMINISTRATOR_TAG HV4D_TYPE_MAXPATH NOT NULL,
CONSTRAINT HV4D_ENUM_ACCESS_LEVEL check(
	PROJECT_INDEX_ACCESS_LEVEL in (
		'LEVEL_1_ACCESS', 
		'LEVEL_2_ACCESS',
		'LEVEL_3_ACCESS',
		'LEVEL_4_ACCESS')));