namespace HV4DUX
{
	[bindable]
	runtimeclass TableContact : Microsoft.UI.Xaml.Controls.UserControl
	{
		TableContact();

	    String LabelUserName;

	    String ValueUserName;

	    String LabelAddressOne;

	    String ValueAddressOne;

	    String LabelAddressTwo;

		String ValueAddressTwo;

		String LabelCity;

	    String ValueCity;

	    String LabelRegion;

	    String ValueRegion;

	    String LabelEMail;

		String ValueEMail;

		String LabelPrimaryPhone;

		String ValuePrimaryPhone;

		String LabelSecondaryPhone;

		String ValueSecondaryPhone;

	}

}
