namespace HV4DUX
{
    [default_interface]
    runtimeclass TableAccountDB : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableAccountDB();

        String LabelAccountDBHost;
        String ValueAccountDBHost;

        String LabelAccountDBRole;
        String ValueAccountDBRole;

        String LabelAccountDBPort;
        String ValueAccountDBPort;

        String LabelAccountDBService;
        String ValueAccountDBService;

        String LabelAccountDBSSLMode;
        String ValueAccountDBSSLMode;

        String LabelAccountDBSSLClientCert;
        String ValueAccountDBSSLClientCert;

        String LabelAccountDBSSLClientKey;
        String ValueAccountDBSSLClientKey;

        String LabelAccountDBSSLRootCert;
        String ValueAccountDBSSLRootCert;

    }
}
