namespace HV4DUX
{
    [default_interface]
    runtimeclass TableAccount : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableAccount();

        String LabelAccountHVID;
        String ValueAccountHVID;

        String LabelAccountID;
        String ValueAccountID;

        String LabelAccountMaxPath;
        String ValueAccountMaxPath;

        String LabelAccountCreated;
        String ValueAccountCreated;

        String LabelAccountUpdated;
        String ValueAccountUpdated;

        String LabelAccountPassword;
        String ValueAccountPassword;

    }

}
