namespace HV4DUX
{
    [bindable]
    runtimeclass TableTNode : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableTNode();

        String LabelHVID;
                
        String ValueHVID;

        String LabelMMM;

        String ValueMMM;

        String LabelName;
                
        String ValueName;
            
        String LabelCreatedDate;
                
        String ValueCreatedDate;
            
        String LabelCreatedTime;
                
        String ValueCreatedTime;
            
        String LabelSavedDate;
                
        String ValueSavedDate;
                        
        String LabelSavedTime;
                
        String ValueSavedTime;
            
        String LabelOpenedDate;
                
        String ValueOpenedDate;
            
        String LabelOpenedTime;
                
        String ValueOpenedTime;

    }

}
