namespace HV4DUX
{
    [default_interface]
    runtimeclass UserMMM : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserMMM();

        String Label;
    
        String ValueMIL;

        String ValueMAJ;

        String ValueMIN;

    }

}
