import "UserMSelectable.idl";

namespace HV4DUX
{
    [bindable]
    runtimeclass UserFilterType : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserFilterType();

        String Label;

        String Value;

        Windows.Foundation.Collections.IObservableVector<UserMSelectable> FilterList;

        UserMSelectable MultiFilterState;

        event Windows.Foundation.EventHandler<String> FilterUpdate;

    }

}
