namespace HV4DUX
{
    [bindable]
    [default_interface]
    runtimeclass UserBlock : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserBlock();

        String Label;

        String Value;

    }

}
