namespace HV4DUX
{
    [bindable]
    runtimeclass UserEntry : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserEntry();

        String Label;

        String Value;
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        String Placeholder;
        
    }

}
