DROP TABLE IF EXISTS HV4D_TABLE_CONTRACT;
CREATE TABLE HV4D_TABLE_CONTRACT(
CONTRACT_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
CONTRACT_ID HV4D_TYPE_ID NOT NULL UNIQUE,
CONTRACT_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
CONTRACT_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
CONTRACT_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
CONTRACT_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(CONTRACT_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (CONTRACT_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));