CREATE TABLE HV4D_TABLE_DEBUG(
PROFILE_HVID HV4D_TYPE_HVID,
DEBUG_HVID HV4D_TYPE_HVID,
DEBUG_MMM HV4D_TYPE_MMM,
DEBUG_TAG HV4D_TYPE_MAXPATH,
DEBUG_COMPILED HV4D_TYPE_DATETIME,
DEBUG_NAMESPACE HV4D_TYPE_MAXPATH,
DEBUG_SERVICE HV4D_TYPE_MAXPATH,
DEBUG_DLL HV4D_TYPE_MAXPATH);