DROP TABLE IF EXISTS HV4D_TABLE_FUNCTION;
CREATE TABLE HV4D_TABLE_FUNCTION(
FUNCTION_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
FUNCTION_ID HV4D_TYPE_ID NOT NULL UNIQUE,
FUNCTION_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
FUNCTION_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
FUNCTION_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
FUNCTION_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(FUNCTION_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (FUNCTION_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));