DROP TABLE IF EXISTS HV4D_TABLE_ACCOUNT;
CREATE TABLE HV4D_TABLE_ACCOUNT(
ACCOUNT_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
ACCOUNT_ID HV4D_TYPE_ID NOT NULL UNIQUE,
ACCOUNT_USER_NAME HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
ACCOUNT_ACCESS_LEVEL HV4D_TYPE_MAXPATH NOT NULL,
ACCOUNT_NAME HV4D_TYPE_MAXPATH NOT NULL,
ACCOUNT_CREATED HV4D_TYPE_DATETIME NOT NULL,
ACCOUNT_UPDATED HV4D_TYPE_DATETIME NOT NULL,
ACCOUNT_PASSWORD HV4D_TYPE_MAXPATH NOT NULL,
ACCOUNT_CONTACT_HVID HV4D_TYPE_HVID NOT NULL,
ACCOUNT_PERMISSIONS HV4D_TYPE_HVID[],
PRIMARY KEY(ACCOUNT_HVID),
CONSTRAINT HV4D_FKEY_CONTACT 
FOREIGN KEY (ACCOUNT_CONTACT_HVID) 
REFERENCES HV4D_TABLE_CONTACT(CONTACT_HVID));