DROP TABLE IF EXISTS HV4D_TABLE_BINDING;
CREATE TABLE HV4D_TABLE_BINDING(
BINDING_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
BINDING_MMM HV4D_TYPE_MMM NOT NULL UNIQUE,
BINDING_TAG HV4D_TYPE_MAXPATH NOT NULL,
BINDING_COMPILED HV4D_TYPE_DATETIME NOT NULL,
BINDING_INSTALLED HV4D_TYPE_DATETIME NOT NULL,
BINDING_UPDATED HV4D_TYPE_DATETIME NOT NULL,
BINDING_DLL_PATH HV4D_TYPE_MAXPATH NOT NULL,
BINDING_DLL HV4D_TYPE_MAXPATH NOT NULL,
BINDING_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
BINDING_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
BINDING_SUPPORTED_CONTRACT HV4D_TYPE_MAXPATH[] NOT NULL,
BINDING_ACCESS_LVL HV4D_TYPE_MAXPATH NOT NULL,
PRIMARY KEY(BINDING_HVID));