DROP TABLE IF EXISTS HV4D_TABLE_WINDOW;
CREATE TABLE HV4D_TABLE_WINDOW(
WINDOW_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
WINDOW_THEME HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_UI_SCALE HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_ANTI_ALIASING HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_FULL_SCREEN HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_RESOLUTION HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_REFRESH_RATE HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_FONT HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_FONT_SIZE HV4D_TYPE_MAXPATH NOT NULL,
WINDOW_FONT_WEIGHT HV4D_TYPE_MAXPATH NOT NULL,
PRIMARY KEY(WINDOW_HVID));