DROP TABLE IF EXISTS HV4D_TABLE_PERMISSION;
CREATE TABLE HV4D_TABLE_PERMISSION(
PERMISSION_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
PERMISSION_TAG HV4D_TYPE_MAXPATH NOT NULL,
PRIMARY KEY(PERMISSION_HVID));