DROP TABLE IF EXISTS HV4D_XAML_PAGE;
CREATE TABLE HV4D_XAML_PAGE(
XAML_PAGE_SERVICE_HVID HV4D_TYPE_HVID NOT NULL,
XAML_PAGE_SERVICE HV4D_TYPE_MAXPATH NOT NULL,
XAML_PAGE_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
XAML_PAGE_ID HV4D_TYPE_ID NOT NULL UNIQUE,
XAML_PAGE_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
XAML_PAGE_SUPPORTED_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
XAML_PAGE_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
XAML_PAGE_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
XAML_PAGE_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
XAML_PAGE_XAML_FILE_PATH HV4D_TYPE_MAXPATH NOT NULL,
XAML_PAGE_XAML_FILE HV4D_TYPE_MAXPATH NOT NULL,
XAML_PAGE_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(XAML_PAGE_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (XAML_PAGE_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));