DROP TABLE IF EXISTS HV4D_TABLE_ENTERPRISE;
CREATE TABLE HV4D_TABLE_ENTERPRISE(
ENTERPRISE_PROFILE_HVID HV4D_TYPE_HVID NOT NULL,
ENTERPRISE_NAME HV4D_TYPE_MAXPATH NOT NULL,
ENTERPRISE_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
ENTERPRISE_REGISTERED HV4D_TYPE_DATETIME NOT NULL,
ENTERPRISE_UPDATED HV4D_TYPE_DATETIME NOT NULL,
ENTERPRISE_LOCALIZATION HV4D_TYPE_MAXPATH NOT NULL,
ENTERPRISE_TIMEZONE HV4D_TYPE_MAXPATH NOT NULL,
ENTERPRISE_KEYBOARD HV4D_TYPE_MAXPATH NOT NULL,
ENTERPRISE_WINDOWS_TARGET HV4D_TYPE_MAXPATH NOT NULL,
ENTERPRISE_EXECUTABLE_DIR HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
ENTERPRISE_ASSETS_DIR HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
ENTERPRISE_XAML_DIR HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
PRIMARY KEY(ENTERPRISE_HVID),
CONSTRAINT HV4D_FKEY_PROFILE FOREIGN KEY(ENTERPRISE_PROFILE_HVID) REFERENCES HV4D_TABLE_PROFILE(PROFILE_HVID));