DROP TABLE IF EXISTS HV4D_TABLE_ITERATOR;
CREATE TABLE HV4D_TABLE_ITERATOR(
ITERATOR_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
ITERATOR_ID HV4D_TYPE_ID NOT NULL UNIQUE,
ITERATOR_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
ITERATOR_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
ITERATOR_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
ITERATOR_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(ITERATOR_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (ITERATOR_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));