DROP TABLE IF EXISTS HV4D_TABLE_STORAGE;
CREATE TABLE HV4D_TABLE_STORAGE(
STORAGE_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
STORAGE_PARTITION_HVID HV4D_TYPE_HVID[] NOT NULL UNIQUE,
PRIMARY KEY(STORAGE_HVID));