DROP TABLE IF EXISTS HV4D_TABLE_GROUP_POLICY;
CREATE TABLE HV4D_TABLE_GROUP_POLICY(
GROUP_POLICY_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
GROUP_POLICY HV4D_TYPE_MAXPATH NOT NULL,
PRIMARY KEY(GROUP_POLICY_HVID));