DROP TABLE IF EXISTS HV4D_TABLE_EVENT;
CREATE TABLE HV4D_TABLE_EVENT(
EVENT_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
EVENT_ID HV4D_TYPE_ID NOT NULL UNIQUE,
EVENT_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
EVENT_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
EVENT_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
EVENT_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(EVENT_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (EVENT_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));