SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_SOFT_DRIVE;
CREATE TABLE HV4D_TABLE_SOFT_DRIVE(
SOFT_DRIVE_HVID HV4D_TYPE_HVID PRIMARY KEY,
SOFT_DRIVE_NAME HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
SOFT_DRIVE_PARTITION HV4D_TYPE_HVID[],
SOFT_DRIVE_CREATED HV4D_TYPE_DATETIME NOT NULL,
SOFT_DRIVE_UPDATED HV4D_TYPE_DATETIME NOT NULL,
SOFT_DRIVE_OPENED HV4D_TYPE_DATETIME NOT NULL,
SOFT_DRIVE_RESERVED HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_DRIVE_ALLOCATED HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_DRIVE_CLUSTER_SIZE HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_DRIVE_PAGE_SIZE HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_DRIVE_ATT_SIZE HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_DRIVE_WHITESPACE_ENCRYPTION HV4D_TYPE_BOOL NOT NULL);