SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_PERMISSION;
CREATE TABLE HV4D_TABLE_PERMISSION(
PERMISSION_HVID HV4D_TYPE_HVID PRIMARY KEY,
PERMISSION_ACCESS_LEVEL HV4D_TYPE_MAXPATH NOT NULL,
PERMISSION_ACCESS_GRANTED HV4D_TYPE_TABLE_REF NOT NULL,
PERMISSION_ACCOUNT_HVID HV4D_TYPE_HVID NOT NULL,
CONSTRAINT HV4D_FKEY_ACCOUNT
	FOREIGN KEY (PERMISSION_ACCOUNT_HVID)
	REFERENCES hv4d_schema_public.HV4D_TABLE_ACCOUNT(ACCOUNT_HVID));