import "IHV4DCOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    [default_interface]
    runtimeclass HV4D_FILE_BAD_FORMATTING : [default] IHV4DCOBJECT, IHV4DRETURN
    {
        HV4D_FILE_BAD_FORMATTING();

        HV4D_FILE_BAD_FORMATTING(IHV4DCOBJECT sender);

        HV4D_FILE_BAD_FORMATTING(IHV4DCOBJECT sender, Guid boxed, Object args);

    }

}