import "IHV4DOBJECT.idl";

namespace HV4D
{
    runtimeclass HV4DRETURN : [default] HV4D.IHV4DOBJECT, IHV4DTTYPE
    {
        HV4DRETURN();

        HV4DRETURN(IHV4DOBJECT sender);

        HV4DRETURN(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}
