namespace HV4D
{
	[uuid("639FB8D2-1E34-4240-9FEE-9F030B5D15B5")]
	[version(0x0001)]
	interface HV4DRETURN
	{
		Guid ReturnType(); //Unique

		UInt64 ID(); //Switch

		String Name(); //If

		UInt64 DateTime(); //Microsoft

		Guid SenderType; //Unique

		Guid SenderHVID; //IInspectable

		Object Sender; //IInspectable

		Guid ExtendedType; //Unique

		Object ExtendedArgs; //Args

		String Comments; //Console.log

	};

}
