import "IHV4DCOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    runtimeclass HV4D_COM_FAILED : [default] IHV4DCOBJECT, IHV4DRETURN
    {
        HV4D_COM_FAILED();

        HV4D_COM_FAILED(IHV4DCOBJECT sender);

        HV4D_COM_FAILED(IHV4DCOBJECT sender, Guid boxed, Object args);

    }

}