import "IHV4DOBJECT.idl";

namespace HV4D
{
    runtimeclass HV4DTTYPE : [default] HV4D.IHV4DOBJECT, IHV4DTTYPE
    {
        HV4DTTYPE();

        HV4DTTYPE(IHV4DOBJECT sender);

        HV4DTTYPE(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}
