import "IHV4DOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    [default_interface]
    runtimeclass HV4D_PROCESS_NOT_FOUND : [default] IHV4DOBJECT, IHV4DRETURN
    {
        HV4D_PROCESS_NOT_FOUND();

        HV4D_PROCESS_NOT_FOUND(IHV4DOBJECT sender);

        HV4D_PROCESS_NOT_FOUND(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}