import "IHV4DOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    [default_interface]
    runtimeclass HV4D_FILE_BAD_FORMATTING : [default] IHV4DOBJECT, IHV4DRETURN
    {
        HV4D_FILE_BAD_FORMATTING();

        HV4D_FILE_BAD_FORMATTING(IHV4DOBJECT sender);

        HV4D_FILE_BAD_FORMATTING(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}