import "IHV4DCOBJECT.idl";
import "IHV4DTTYPE.idl";

namespace HV4D
{
    runtimeclass HV4DT_TYPE_LIBRARY : [default] IHV4DCOBJECT, IHV4DTTYPE
    {
        HV4DT_TYPE_LIBRARY();

        HV4DT_TYPE_LIBRARY(IHV4DCOBJECT sender);

        HV4DT_TYPE_LIBRARY(IHV4DCOBJECT sender, Guid boxed, Object args);

    }

}