namespace HV4D
{
    [uuid("CD7DFCE5-3208-424A-8498-3D96E011821A")]
    [version(0x10000001)]
    interface IHV4DOBJECT
    {
        Guid HV4DSpecializationType();

        UInt64 HV4DSpecializationID();

        String HV4DSpecializationName();

        Guid HV4DInstanceHVID();

        UInt64 HV4DCreatedDateTime();

        UInt64 HV4DUpdatedDateTime();

    }

}
