import "IHV4DCOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    [default_interface]
    runtimeclass HV4D_NO_FILE_OPEN : [default] IHV4DCOBJECT, IHV4DRETURN
    {
        HV4D_NO_FILE_OPEN();

        HV4D_NO_FILE_OPEN(IHV4DCOBJECT sender);

        HV4D_NO_FILE_OPEN(IHV4DCOBJECT sender, Guid boxed, Object args);

    }

}