import "IHV4DOBJECT.idl";

namespace HV4D
{
    runtimeclass HV4DOBJECT : [default] HV4D.IHV4DOBJECT, IHV4DTTYPE
    {
        HV4DOBJECT();

        HV4DOBJECT(IHV4DOBJECT sender);

        HV4DOBJECT(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}
