import "IHV4DCOBJECT.idl";
import "IHV4DRETURN.idl";

namespace HV4D
{
    [default_interface]
    runtimeclass HV4D_OPERATION_SUCCEEDED : [default] IHV4DCOBJECT, IHV4DRETURN
    {
        HV4D_OPERATION_SUCCEEDED();

        HV4D_OPERATION_SUCCEEDED(IHV4DCOBJECT sender);

        HV4D_OPERATION_SUCCEEDED(IHV4DCOBJECT sender, Guid boxed, Object args);

    }

}