import "IHV4DOBJECT.idl";
import "IHV4DTTYPE.idl";

namespace HV4D
{
    runtimeclass HV4DT_TYPE_LIBRARY : [default] IHV4DOBJECT, IHV4DTTYPE
    {
        HV4DT_TYPE_LIBRARY();

        HV4DT_TYPE_LIBRARY(IHV4DOBJECT sender);

        HV4DT_TYPE_LIBRARY(IHV4DOBJECT sender, Guid boxed, Object args);

    }

}