import "IHV4DRETURN.idl";

namespace HV4D
{
	[uuid("89CA4C6E-30F4-4EB2-B1FF-0D5321853283")]
	[version(0x10000001)]
	interface IHV4DBROKER
	{
		IHV4DRETURN HV4DSetBrokerData(Windows.Foundation.Collections.IMap<Guid, Object> broker);

		IHV4DRETURN HV4DGetBrokerData(Windows.Foundation.Collections.IMap<Guid, Object> broker);

	};

}
