namespace HV4D
{
	[uuid("C306CFBA-8DD6-4A03-8DE5-9C3329111EC1")]
    [version(0x10000001)]
    interface IHV4DINSTANCE
    {
		Guid HV4DUuidOfInstance();

		UInt64 HV4DCreatedDateTime();

		UInt64 HV4DUpdatedDateTime();

		Guid HV4DUuidOfCollection();

		Guid HV4DUuidOfClassObject();

		String HV4DNameOfClassObject();

		Guid HV4DUuidOfClassObjectSet();

    }

}
