import "IHV4DSERVICE.idl";

namespace HV4D
{
	[uuid("89CA4C6E-30F4-4EB2-B1FF-0D5321853283")]
	[version(0x10000001)]
	interface IHV4DTTYPE
	{
		Guid HV4DGetTTypeUuid();

		Guid HV4DGetTTypeId();

		String HV4DGetTTypeName();

		IHV4DSERVICE HV4DGetService();

	};

}
