import "IHV4DRETURN.idl";

namespace HV4D
{
    [uuid("99B07AB6-E4F6-47B3-9498-E04ABE6CD93C")]
    [version(0x10000001)]
    interface IHV4DCOBJECT
    {
         IHV4DRETURN HV4DSupportedInterfaces(Windows.Foundation.Collections.IMap<Guid, Object> interfaces);

    }

}
