import "IHV4DITERATOR.idl";
import "IHV4DCONTRACT.idl";

namespace HV4D
{
    [uuid("99B07AB6-E4F6-47B3-9498-E04ABE6CD93C")]
    [version(0x10000001)]
    interface IHV4DCOBJECT
    {
        Windows.Foundation.Collections.IMap<IHV4DITERATOR, IHV4DCONTRACT> HV4DSupportedInterfaces();

    }

}
