import "IHV4DCOBJECT.idl";

namespace HV4D
{
    [uuid("49517524-B769-480F-BBA5-14549B2CD394")]
    [version(0x10000001)]
    interface IHV4DEXTARGS
    {
        IHV4DCOBJECT HV4DSender;

        Guid HV4DExtendedArgsType;

        Object HV4DExtendedArgs;

        String HV4DComments;

    }

}
