import "IHV4DRETURN.idl";

namespace HV4D
{
	[uuid("C306CFBA-8DD6-4A03-8DE5-9C3329111EC1")]
    [version(0x10000001)]
    interface IHV4DINSTANCE
    {
		IHV4DRETURN HV4DSetInstanceData(Windows.Foundation.Collections.IMap<Guid, Object> instance);

		IHV4DRETURN HV4DGetInstanceData(Windows.Foundation.Collections.IMap<Guid, Object> instance);

    }

}
