import "IHV4DOBJECT.idl";

namespace HV4D
{
	[uuid("639FB8D2-1E34-4240-9FEE-9F030B5D15B5")]
	[version(0x10000001)]
	interface IHV4DRETURN
	{
		HV4D.IHV4DOBJECT HV4DSender;

		Guid HV4DReturnTypeUid();

		UInt64 HV4DReturnTypeID();

		String HV4DReturnTypeName();

		Guid HV4DExtendedArgsType;

		Object HV4DExtendedArgs;

		String HV4DComments;

	};

}
