import "IHV4DOBJECT.idl";

namespace HV4D
{
	[uuid("35BB4645-E9B1-4062-BCB4-F1E3FF7E94F8")]
	[version(0x10000001)]
	interface IHV4DTTYPE
	{
		HV4D.IHV4DOBJECT HV4DSender;

		Guid HV4DTTypeUid();

		UInt64 HV4DTTypeID();

		String HV4DTTypeName();

		Guid HV4DExtendedArgsType;

		Object HV4DExtendedArgs;

		String HV4DComments;

	};

}
