namespace HV4DABI
{
	[uuid(79DE12A9-7834-478D-A3B5-AAC0709CDE50)]
	[version(0x10000001)]
	interface IMeta : IInspectable
	{
		 HV4D.HV4DRETURN HV4DLoadMetaDataFromFile();

	};

    [default_interface]
    runtimeclass HV4DMETA
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DMETA();


    }

}
