namespace HV4DABI
{
    struct CLASST {
        String ns;
        String	c;
    };

    [default_interface]
    runtimeclass HV4DCLASST
        : HV4DT.IHV4DTPROVIDER
    {
        HV4DCLASST();
    
		HV4D.IHV4DRETURN HV4DFromHstring(String p, String f);

		HV4D.IHV4DRETURN HV4DFromABI(CLASST t);

		HV4D.IHV4DRETURN HV4DFromWinRT(HV4DCLASST t);

		HV4D.IHV4DRETURN HV4DToHstring(out String p, out String f);

		HV4D.IHV4DRETURN HV4DToABI(out CLASST t);

		HV4D.IHV4DRETURN HV4DToWinRT(out HV4DCLASST t);

		HV4D.IHV4DRETURN HV4DIsEqualHstring(String p, String f);

		HV4D.IHV4DRETURN HV4DIsEqualABI(CLASST t);

		HV4D.IHV4DRETURN HV4DIsEqualWinRT(HV4DCLASST t);


    }

}
