import "HV4DNUMERIC.idl";

namespace HV4DABI
{
	struct OFFSET {
		NUMERIC   o;
		NUMERIC  sz;
	};

    [default_interface]
    runtimeclass HV4DOFFSET
		: HV4DT.IHV4DTPROVIDER
    {
        HV4DOFFSET();
    
		HV4D.HV4DRETURN HV4DFromHstring(String off, String sz);

		HV4D.HV4DRETURN HV4DFromUInt64(UInt64 off, UInt64 sz);

		HV4D.HV4DRETURN HV4DFromABI(OFFSET e);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DOFFSET e);

		HV4D.HV4DRETURN HV4DToUInt64(out UInt64 off, out UInt64 sz);

		HV4D.HV4DRETURN HV4DToHstring(out String off, out String sz);

		HV4D.HV4DRETURN HV4DToABI(out OFFSET e);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DOFFSET e);

		HV4D.HV4DRETURN HV4DIsEqualUInt64(UInt64 off, UInt64 sz);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String off, String sz);

		HV4D.HV4DRETURN HV4DIsEqualABI(OFFSET e);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DOFFSET e);

    }

}
