import "HV4DHVID.h";
import "HV4DMMM.h";
import "HV4DMAXPATH.h";
import "HV4DABS.h";
import "HV4DCLASST.h";

namespace HV4DABI
	: HV4DT.IHV4DTPROVIDER
{
	struct RTCLASS {
		HVID		hvid;
		MMM			 mmm;
		MAXPATH		name;
		ABS			 dll;
		CLASST	  classt;
	};

    [default_interface]
    runtimeclass HV4DRTCLASS
    {
        HV4DRTCLASS();


    }

}
