namespace HV4DABI
{
    [uuid(8B798CC7-005A-4B82-9F29-DC86714B7825)]
    [version(0x10000001)]
    interface IAsync : IInspectable
    {


    };

    [default_interface]
    runtimeclass HV4DASYNC
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DASYNC();


    }

}
