namespace HV4DABI
{
	struct HHMMSS {
		String hh;
		String mm;
		String ss;
	};

    [default_interface]
    runtimeclass HV4DHHMMSS
		: HV4DT.IHV4DTPROVIDER
    {
        HV4DHHMMSS();
	
		HV4D.HV4DRETURN HV4DFromHstring(String e);

		HV4D.HV4DRETURN HV4DFromABI(HHMMSS e);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DHHMMSS e);

		HV4D.HV4DRETURN HV4DToHstring(out String e);

		HV4D.HV4DRETURN HV4DToABI(out HHMMSS e);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DHHMMSS e);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String e);

		HV4D.HV4DRETURN HV4DIsEqualABI(HHMMSS e);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DHHMMSS e);

    }

}
