namespace HV4DABI
{
	struct MAXPATH {
		String mp;
	};

    [default_interface]
    runtimeclass HV4DMAXPATH
		: HV4DT.IHV4DTPROVIDER
    {
        HV4DMAXPATH();
    
		HV4D.HV4DRETURN HV4DFromHstring(String e);

		HV4D.HV4DRETURN HV4DFromABI(MAXPATH e);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DMAXPATH e);

		HV4D.HV4DRETURN HV4DToHstring(out String e);

		HV4D.HV4DRETURN HV4DToABI(out MAXPATH e);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DMAXPATH e);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String e);

		HV4D.HV4DRETURN HV4DIsEqualABI(MAXPATH e);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DMAXPATH e);

    }

}
