namespace HV4DABI
{
    [uuid(B0344658-8549-4D45-8CBE-96A89144B1AB)]
    [version(0x10000001)]
    interface IShell : IInspectable
    {


    };

    [default_interface]
    runtimeclass HV4DSHELL
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DSHELL();


    }

}
