namespace HV4DABI
{
	[uuid(A7FB51C5-C758-4863-811B-3F1EF721087C)]
	[version(0x10000001)]
	interface IKernel : IInspectable
	{
		 HV4D.HV4DRETURN HV4DKernalScriptFromFile();

	};

    [default_interface]
    runtimeclass HV4DKERNEL
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DKERNEL();


    }

}
