import "HV4DHstringFromGUID.idl";
import "HV4DFILE.idl";

namespace HV4DABI
{
	[uuid(F153E6F2-073F-4E5E-BE59-69285CD53B6E)]
	[version(0x10000001)]
	interface IHV4DTREE : IInspectable
	{
		HV4D.HV4DRETURN HV4DCurrentDir(HV4DHstringFromGUID r, out String d);

		HV4D.HV4DRETURN HV4DDirTree(HV4DHstringFromGUID r, out String[] d);

		HV4D.HV4DRETURN HV4DListFiles(HV4DHstringFromGUID r, out String[] f);

		HV4D.HV4DRETURN HV4DDirChange(HV4DHstringFromGUID r, String d);

		HV4D.HV4DRETURN HV4DMkDir(HV4DHstringFromGUID r, String d);

		HV4D.HV4DRETURN HV4DDelDir(HV4DHstringFromGUID r, String d);

		HV4D.HV4DRETURN HV4DCopyTree(HV4DHstringFromGUID r, String p, String q);

		HV4D.HV4DRETURN HV4DDelTree(HV4DHstringFromGUID r, String d);

		HV4D.HV4DRETURN HV4DOpenFile(HV4DHstringFromGUID r, String f, IFile l);

		HV4D.HV4DRETURN HV4DCloseFile(Boolean b, IFile e);

		HV4D.HV4DRETURN HV4DSaveFile(IFile e);

		HV4D.HV4DRETURN HV4DMoveFile(HV4DHstringFromGUID r, String p, String q, IFile e, IFile l);

		HV4D.HV4DRETURN HV4DDelFile(HV4DHstringFromGUID r, IFile e, String f);

		HV4D.HV4DRETURN HV4DVolumeSize(out UInt32 u, out UInt32 v, out UInt32 s);

	}

    [default_interface]
    runtimeclass HV4DTREE
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DTREE();


    }

}
