#include "pch.h"
#include "HV4DNUMERIC.h"
#if __has_include("HV4DNUMERIC.g.cpp")
#include "HV4DNUMERIC.g.cpp"
#endif

using namespace winrt;

using namespace winrt::HV4D;

namespace winrt::HV4DABI::implementation
{
	HV4DNUMERIC::HV4DNUMERIC()
	{

		return;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromUInt8(uint8_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromUInt16(uint16_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromUInt32(uint32_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromUInt64(uint64_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromABI(NUMERIC const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DFromWinRT(winrt::HV4DABI::HV4DNUMERIC const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToUInt8(uint8_t&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToUInt16(uint16_t&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToUInt32(uint32_t&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToUInt64(uint64_t&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToHstring(hstring&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToABI(NUMERIC&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DToWinRT(winrt::HV4DABI::HV4DNUMERIC&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualUInt8(uint8_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualUInt16(uint16_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualUInt32(uint32_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualUInt64(uint64_t const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualABI(NUMERIC const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DNUMERIC::HV4DIsEqualWinRT(winrt::HV4DABI::HV4DNUMERIC const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

}
