namespace HV4DABI
{
    struct ABS {
        String p;
        String f;
    };

    [default_interface]
    runtimeclass HV4DABS
        : HV4DT.IHV4DTPROVIDER
    {
        HV4DABS();
    
		HV4D.HV4DRETURN HV4DFromHstring(String p, String f);

		HV4D.HV4DRETURN HV4DFromABI(ABS abs);

		HV4D.HV4DRETURN HV4DFromWinRT(HV4DABS abs);

		HV4D.HV4DRETURN HV4DToHstring(out String p, out String f);

		HV4D.HV4DRETURN HV4DToABI(out ABS abs);

		HV4D.HV4DRETURN HV4DToWinRT(out HV4DABS abs);

		HV4D.HV4DRETURN HV4DIsEqualHstring(String p, String f);

		HV4D.HV4DRETURN HV4DIsEqualABI(ABS abs);

		HV4D.HV4DRETURN HV4DIsEqualWinRT(HV4DABS abs);

    }

}
