#include "pch.h"
#include "HV4DMAXPATH.h"
#if __has_include("HV4DMAXPATH.g.cpp")
#include "HV4DMAXPATH.g.cpp"
#endif

using namespace winrt;

using namespace winrt::HV4D;

namespace winrt::HV4DABI::implementation
{
	HV4DMAXPATH::HV4DMAXPATH()
	{

		return;

	}

	HV4DRETURN HV4DMAXPATH::HV4DFromHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DFromABI(MAXPATH const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DFromWinRT(winrt::HV4DABI::HV4DMAXPATH const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DToHstring(hstring&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DToABI(MAXPATH&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DToWinRT(winrt::HV4DABI::HV4DMAXPATH)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DIsEqualHstring(hstring const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DIsEqualABI(MAXPATH const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

	HV4DRETURN HV4DMAXPATH::HV4DIsEqualWinRT(winrt::HV4DABI::HV4DMAXPATH const&)
	{

		return HV4DRETURN::HV4D_OPERATION_SUCCEEDED;

	}

}
