import "HV4DMMDDYYYY.idl";
import "HV4DHHMMSS.idl";

namespace HV4DTBASIC
{
    runtimeclass HV4DDATETIME : [default] HV4D.IHV4DCOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DDATETIME();

		HV4DDATETIME(HV4D.IHV4DCOBJECT sender);

		HV4DDATETIME(HV4D.IHV4DCOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DDATETIMEFromHstring(String d, String t);

		HV4D.IHV4DRETURN HV4DDATETIMEFromHV4D(HV4DMMDDYYYY d, HV4DHHMMSS t);

		HV4D.IHV4DRETURN HV4DDATETIMEFromProj(HV4DDATETIME e);

		HV4D.IHV4DRETURN HV4DDATETIMEToHstring(out String d, out String t);

		HV4D.IHV4DRETURN HV4DDATETIMEToHV4D(out HV4DMMDDYYYY d, out HV4DHHMMSS t);

		HV4D.IHV4DRETURN HV4DDATETIMEToProj(out HV4DDATETIME e);

		HV4D.IHV4DRETURN HV4DDATETIMEIsEqualHstring(String d, String t);

		HV4D.IHV4DRETURN HV4DDATETIMEIsEqualHV4D(HV4DMMDDYYYY d, HV4DHHMMSS t);

		HV4D.IHV4DRETURN HV4DDATETIMEIsEqualProj(HV4DDATETIME e);

		HV4D.IHV4DRETURN HV4DSetToCurrentDATETIME();

    }

}