namespace HV4DTBASIC
{
	struct MAXPATH {
		String mp;
	};

    runtimeclass HV4DMAXPATH : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
        HV4DMAXPATH();
    
		HV4D.IHV4DRETURN HV4DFromHstring(String e);

		HV4D.IHV4DRETURN HV4DFromABI(MAXPATH e);

		HV4D.IHV4DRETURN HV4DFromWinRT(HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DToHstring(out String e);

		HV4D.IHV4DRETURN HV4DToABI(out MAXPATH e);

		HV4D.IHV4DRETURN HV4DToWinRT(out HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DIsEqualHstring(String e);

		HV4D.IHV4DRETURN HV4DIsEqualABI(MAXPATH e);

		HV4D.IHV4DRETURN HV4DIsEqualWinRT(HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DSubStr(UInt32 i, UInt32 l, out HV4DMAXPATH o);

    }

}
