import "HV4DMAXPATH.idl";

namespace HV4DTBASIC
{
    runtimeclass HV4DABS : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
        HV4DABS();
 
		HV4DABS(HV4D.IHV4DOBJECT sender);

		HV4DABS(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DABSFromHstring(String p, String f);

		HV4D.IHV4DRETURN HV4DABSFromMAXPATH(HV4DMAXPATH p, HV4DMAXPATH f);

		HV4D.IHV4DRETURN HV4DABSFromProj(HV4DABS e);

		HV4D.IHV4DRETURN HV4DABSToHstring(out String p, out String f);

		HV4D.IHV4DRETURN HV4DABSToMAXPATH(out HV4DMAXPATH p, out HV4DMAXPATH f);

		HV4D.IHV4DRETURN HV4DABSToProj(out HV4DABS e);

		HV4D.IHV4DRETURN HV4DABSIsEqualHstring(String p, String f);

		HV4D.IHV4DRETURN HV4DABSIsEqualMAXPATH(HV4DMAXPATH p, HV4DMAXPATH f);

		HV4D.IHV4DRETURN HV4DABSIsEqualProj(HV4DABS e);

    }

}
