namespace HV4DTBASIC
{
	runtimeclass HV4DHHMMSS : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DHHMMSS();

		HV4DHHMMSS(HV4D.IHV4DOBJECT sender);

		HV4DHHMMSS(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DHHMMSSFromHstring(String n);

		HV4D.IHV4DRETURN HV4DHHMMSSFromProj(HV4DHHMMSS e);

		HV4D.IHV4DRETURN HV4DHHMMSSToHstring(out String n);

		HV4D.IHV4DRETURN HV4DHHMMSSToProj(out HV4DHHMMSS e);

		HV4D.IHV4DRETURN HV4DHHMMSSIsEqualHstring(String n);

		HV4D.IHV4DRETURN HV4DHHMMSSIsEqualProj(HV4DHHMMSS e);

		HV4D.IHV4DRETURN HV4DSetToCurrentTime();

    }

}
