namespace HV4DTBASIC
{
    runtimeclass HV4DALPHANUMERIC : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DRETURN
    {
        HV4DALPHANUMERIC();

        HV4DALPHANUMERIC(HV4D.IHV4DOBJECT sender);

        HV4DALPHANUMERIC(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DALPHANUMERICFromHstring(String n);

		HV4D.IHV4DRETURN HV4DALPHANUMERICFromProj(HV4DALPHANUMERIC e);

		HV4D.IHV4DRETURN HV4DALPHANUMERICToHstring(out String n);

		HV4D.IHV4DRETURN HV4DALPHANUMERICToProj(out HV4DALPHANUMERIC e);

		HV4D.IHV4DRETURN HV4DALPHANUMERICIsEqualHstring(String n);

		HV4D.IHV4DRETURN HV4DALPHANUMERICIsEqualProj(HV4DALPHANUMERIC e);


    }

}