namespace HV4DTBASIC
{
    runtimeclass HV4DHVID : [default] HV4D.IHV4DCOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DHVID();

		HV4DHVID(HV4D.IHV4DCOBJECT sender);

		HV4DHVID(HV4D.IHV4DCOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DHVIDFromHstring(String uid);

		HV4D.IHV4DRETURN HV4DHVIDFromGuid(Guid uid);

		HV4D.IHV4DRETURN HV4DHVIDFromProj(HV4DHVID e);

		HV4D.IHV4DRETURN HV4DHVIDToHstring(out String uid);

		HV4D.IHV4DRETURN HV4DHVIDToGuid(out Guid uid);

		HV4D.IHV4DRETURN HV4DHVIDToProj(out HV4DHVID e);

		HV4D.IHV4DRETURN HV4DHVIDIsEqualHstring(String uid);

		HV4D.IHV4DRETURN HV4DHVIDIsEqualGuid(Guid uid);

		HV4D.IHV4DRETURN HV4DHHVIDIsEqualProj(HV4DHVID e);

		HV4D.IHV4DRETURN HV4DSetToRandomHVID();

    }

}
