import "HV4DNUMERIC.idl";

namespace HV4DTBASIC
{
    runtimeclass HV4DOFFSET : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DOFFSET();

		HV4DOFFSET(HV4D.IHV4DOBJECT sender);

		HV4DOFFSET(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DOFFSETFromHstring(String off, String sz);

		HV4D.IHV4DRETURN HV4DOFFSETFromNUM(UInt64 off, UInt64 sz);

		HV4D.IHV4DRETURN HV4DOFFSETFromProj(HV4DOFFSET e);

		HV4D.IHV4DRETURN HV4DOFFSETToNUM(out UInt64 off, out UInt64 sz);

		HV4D.IHV4DRETURN HV4DOFFSETToHstring(out String off, out String sz);

		HV4D.IHV4DRETURN HV4DOFFSETToProj(out HV4DOFFSET e);

		HV4D.IHV4DRETURN HV4DOFFSETIsEqualNUM(UInt64 off, UInt64 sz);

		HV4D.IHV4DRETURN HV4DOFFSETIsEqualHstring(String off, String sz);

		HV4D.IHV4DRETURN HV4DOFFSETIsEqualProj(HV4DOFFSET e);

    }

}
