namespace HV4DTBASIC
{
	struct MMM {
		String  mil;
		String  maj;
		String  min;
	};

    runtimeclass HV4DMMM : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
        HV4DMMM();
    
		HV4D.IHV4DRETURN HV4DFromHstring(String e);
	
		HV4D.IHV4DRETURN HV4DFromABI(MMM e);
	
		HV4D.IHV4DRETURN HV4DFromWinRT(HV4DMMM e);
	
		HV4D.IHV4DRETURN HV4DToHstring(out String e);
	
		HV4D.IHV4DRETURN HV4DToABI(out MMM e);
	
		HV4D.IHV4DRETURN HV4DToWinRT(out HV4DMMM e);
	
		HV4D.IHV4DRETURN HV4DIsEqualHstring(String e);
	
		HV4D.IHV4DRETURN HV4DIsEqualABI(MMM e);
	
		HV4D.IHV4DRETURN HV4DIsEqualWinRT(HV4DMMM e);
	

    }

}
