namespace HV4DTBASIC
{
    runtimeclass HV4DMMDDYYYY : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DMMDDYYYY();

		HV4DMMDDYYYY(HV4D.IHV4DOBJECT sender);

		HV4DMMDDYYYY(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DMMDDYYYYFromHstring(String s);

		HV4D.IHV4DRETURN HV4DMMDDYYYYFromProj(HV4DMMDDYYYY e);

		HV4D.IHV4DRETURN HV4DMMDDYYYYToHstring(out String s);

		HV4D.IHV4DRETURN HV4DMMDDYYYYToProj(out HV4DMMDDYYYY e);

		HV4D.IHV4DRETURN HV4DMMDDYYYYIsEqualHstring(String s);

		HV4D.IHV4DRETURN HV4DMMDDYYYYIsEqualProj(HV4DMMDDYYYY e);

		HV4D.IHV4DRETURN HV4DSetToCurrentDate();

    }

}
