namespace HV4DTBASIC
{
    runtimeclass HV4DHEX : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DHEX();

		HV4DHEX(HV4D.IHV4DOBJECT sender);

		HV4DHEX(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DHEXFromHstring(String n);

		HV4D.IHV4DRETURN HV4DHEXFromNUM(UInt64 n);

		HV4D.IHV4DRETURN HV4DHEXFromProj(HV4DHEX e);

		HV4D.IHV4DRETURN HV4DHEXToHstring(out String n);

		HV4D.IHV4DRETURN HV4DHEXToNUM(out UInt64 n);

		HV4D.IHV4DRETURN HV4DHEXToProj(out HV4DHEX e);

		HV4D.IHV4DRETURN HV4DHEXIsEqualHstring(String n);

		HV4D.IHV4DRETURN HV4DHEXIsEqualNUM(UInt64 n);

		HV4D.IHV4DRETURN HV4DHEXIsEqualProj(HV4DHEX e);

    }

}