namespace HV4DTBASIC
{
    runtimeclass HV4DNUMERIC : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DNUMERIC();

		HV4DNUMERIC(HV4D.IHV4DOBJECT sender);

		HV4DNUMERIC(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DNUMERICFromNUM(UInt64 n);

		HV4D.IHV4DRETURN HV4DNUMERICFromHstring(String n);

		HV4D.IHV4DRETURN HV4DNUMERICFromProj(HV4DNUMERIC e);

		HV4D.IHV4DRETURN HV4DNUMERICToNUM(out UInt64 e);

		HV4D.IHV4DRETURN HV4DNUMERICToHstring(out String e);

		HV4D.IHV4DRETURN HV4DNUMERICToProj(out HV4DNUMERIC e);

		HV4D.IHV4DRETURN HV4DNUMERICIsEqualNUM(UInt64 e);

		HV4D.IHV4DRETURN HV4DNUMERICIsEqualHstring(String e);

		HV4D.IHV4DRETURN HV4DNUMERICIsEqualProj(HV4DNUMERIC e);

    }

}
