namespace HV4DTBASIC
{
	runtimeclass HV4DTEXTBLOBW : [default] HV4D.IHV4DCOBJECT, HV4D.IHV4DTTYPE
	{
		HV4DTEXTBLOBW();

		HV4DTEXTBLOBW(HV4D.IHV4DCOBJECT sender);

		HV4DTEXTBLOBW(HV4D.IHV4DCOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWFromHstring(String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWFromProj(HV4DTEXTBLOBW e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWToHstring(out String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWToProj(out HV4DTEXTBLOBW e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWIsEqualHstring(String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWIsEqualProj(HV4DTEXTBLOBW e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBWSubStr(UInt32 i, UInt32 l, out HV4DTEXTBLOBW o);

	}

}