namespace HV4DTBASIC
{
    runtimeclass HV4DTEXTBLOBA : [default] HV4D.IHV4DCOBJECT, HV4D.IHV4DTTYPE
    {
        HV4DTEXTBLOBA();

        HV4DTEXTBLOBA(HV4D.IHV4DCOBJECT sender);

        HV4DTEXTBLOBA(HV4D.IHV4DCOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAFromHstring(String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAFromProj(HV4DTEXTBLOBA e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAToHstring(out String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAToProj(out HV4DTEXTBLOBA e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAIsEqualHstring(String e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBAIsEqualProj(HV4DTEXTBLOBA e);

		HV4D.IHV4DRETURN HV4DTEXTBLOBASubStr(UInt64 i, UInt64 l, out HV4DTEXTBLOBA o);

    }

}