namespace HV4DTBASIC
{
    runtimeclass HV4DMAXPATH : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DMAXPATH();

		HV4DMAXPATH(HV4D.IHV4DOBJECT sender);

		HV4DMAXPATH(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DMAXPATHFromHstring(String e);

		HV4D.IHV4DRETURN HV4DMAXPATHFromProj(HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DMAXPATHToHstring(out String e);

		HV4D.IHV4DRETURN HV4DMAXPATHToProj(out HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DMAXPATHIsEqualHstring(String e);

		HV4D.IHV4DRETURN HV4DMAXPATHIsEqualProj(HV4DMAXPATH e);

		HV4D.IHV4DRETURN HV4DMAXPATHSubStr(UInt64 i, UInt64 l, out HV4DMAXPATH o);

    }

}
