namespace HV4DTBASIC
{
    runtimeclass HV4DMMM : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
		HV4DMMM();

		HV4DMMM(HV4D.IHV4DOBJECT sender);

		HV4DMMM(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DMMMFromHstring(String e);
	
		HV4D.IHV4DRETURN HV4DMMMFromProj(HV4DMMM e);
	
		HV4D.IHV4DRETURN HV4DMMMToHstring(out String e);
	
		HV4D.IHV4DRETURN HV4DMMMToProj(out HV4DMMM e);
	
		HV4D.IHV4DRETURN HV4DMMMIsEqualHstring(String e);
	
		HV4D.IHV4DRETURN HV4DMMMIsEqualProj(HV4DMMM e);
	
    }

}
