import "HV4DMAXPATH.idl";

namespace HV4DTBASIC
{
    runtimeclass HV4DCLASST : [default] HV4D.IHV4DOBJECT, HV4D.IHV4DTTYPE
    {
        HV4DCLASST();
    
        HV4DCLASST(HV4D.IHV4DOBJECT sender);

		HV4DCLASST(HV4D.IHV4DOBJECT sender, Guid boxed, Object args);

		HV4D.IHV4DRETURN HV4DCLASSTFromHstring(String ns, String c);

		HV4D.IHV4DRETURN HV4DCLASSTFromMAXPATH(HV4DMAXPATH ns, HV4DMAXPATH c);

		HV4D.IHV4DRETURN HV4DCLASSTFromProj(HV4DCLASST e);

		HV4D.IHV4DRETURN HV4DCLASSTToHstring(out String ns, out String c);

		HV4D.IHV4DRETURN HV4DCLASSTToHV4DMAXPATH(out HV4DMAXPATH ns, out HV4DMAXPATH c);

		HV4D.IHV4DRETURN HV4DCLASSTToProj(out HV4DCLASST e);

		HV4D.IHV4DRETURN HV4DCLASSTIsEqualHstring(String ns, String c);

		HV4D.IHV4DRETURN HV4DCLASSTIsEqualHV4DMAXPATH(HV4DMAXPATH ns, HV4DMAXPATH c);

		HV4D.IHV4DRETURN HV4DCLASSTIsEqualProj(HV4DCLASST e);

    }

}
