namespace HV4DX
{
    [default_interface]
    runtimeclass TableContractItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableContractItem();
    
        void SelectDefaultFromTables(String uid);

    }

}
