namespace HV4DX
{
    [default_interface]
    runtimeclass TableParameterItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableParameterItem();
    
        void SelectDefaultFromTables(String uid);

    }

}
