namespace HV4DX
{
    [default_interface]
    runtimeclass TableAccount : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableAccount();

        String TableKey{ get; };
	
        void SelectDefaultFromTables(String uid);

    }

}
