namespace HV4DX
{
    [default_interface]
    runtimeclass TableAccountPort : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableAccountPort();

        String ValueKey;

        void SelectDefaultFromTables(String uid);
            
    }

}
