namespace HV4DX
{
    [default_interface]
    runtimeclass TableXamlWidget : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableXamlWidget();
        
        void SelectDefaultFromTables(String uid);

    }

}
