namespace HV4DX
{
    [default_interface]
    runtimeclass TableIttItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableIttItem();
 
        void SelectDefaultFromTables(String uid);

    }

}
