namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableIttLibrary : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableIttLibrary();
 
        void SelectDefaultFromTables(String uid);

    }

}
