namespace HV4DX
{
    [default_interface]
    runtimeclass TableFunctionItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableFunctionItem();
    
        void SelectDefaultFromTables(String uid);

    }

}
