namespace HV4DX
{
    [default_interface]
    runtimeclass TableXamlResource : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableXamlResource();
        
        void SelectDefaultFromTables(String uid);

    }

}
