import "TablePartition.idl";

namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableStorage : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableStorage();
    
        void SelectDefaultFromTables(String uid);

    }

}
