namespace HV4DX
{
    [default_interface]
    runtimeclass TableIndex : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableIndex();

        String LabelIndexHVID;
        String ValueIndexHVID;
        String LabelIndexMMM;
        String ValueIndexMIL;
        String ValueIndexMAJ;
        String ValueIndexMIN;
        String LabelIndexMaxPath;
        String ValueIndexMaxPath;
        String LabelIndexCreated;
        String ValueIndexCreated;
        String LabelIndexSaved;
        String ValueIndexSaved;
        String LabelIndexOpened;
        String ValueIndexOpened;

    }

}
