namespace HV4DX
{
    [default_interface]
    runtimeclass TableProfile : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableProfile();

        String LabelProfileHVID;
        UInt32 IndexProfileHVID;
        Windows.Foundation.Collections.IObservableVector<String> ListProfileHVID;

        String LabelProfileMMM;
        String ValueProfileMIL;
        String ValueProfileMAJ;
        String ValueProfileMIN;

        String LabelProfileMaxPath;
        UInt32 IndexProfileMaxPath;
        Windows.Foundation.Collections.IObservableVector<String> ListProfileID;

        String LabelProfileCreated;
        String ValueProfileCreated;
        String LabelProfileSaved;
        String ValueProfileSaved;
        String LabelProfileOpened;
        String ValueProfileOpened;

    }

}
