namespace HV4DX
{
    [default_interface]
    runtimeclass TableAccountNew : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TableAccountNew();
    
        String TableKey{ get; };
	
        void SelectDefaultFromTables(String uid);

    }

}
