namespace HV4DX
{
    [default_interface]
    runtimeclass TableXamlContextMenu : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableXamlContextMenu();
        
        void SelectDefaultFromTables(String uid);

    }

}
