namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableContrLibrary : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableContrLibrary();
    
        void SelectDefaultFromTables(String uid);

    }

}
