namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableDigitalTwin : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableDigitalTwin();
    
        void SelectDefaultFromTables(String uid);

    }

}
