namespace HV4DX
{
    [default_interface]
    runtimeclass TableAccountNew : Microsoft.UI.Xaml.Controls.Page
    {
        TableAccountNew();
    
        String ValueKey;
	
        void SelectDefaultFromTables(String uid);

    }

}
