namespace HV4DX
{
    [default_interface]
    runtimeclass TableProfile : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableProfile();

        String LabelProfileHVID{ get; };
        String LabelProfileMMM{ get; };
        String LabelProfileMaxPath{ get; };
        String LabelProfileCreated{ get; };
        String LabelProfileSaved{ get; };
        String LabelProfileOpened{ get; };

    }

}
