namespace HV4DX
{
    [default_interface]
    runtimeclass TableIttItem : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableIttItem();
    /*
        String LabelIttLibraryHVID;
        String ValueIttLibraryHVID;
        String LabelIttLibraryID;
        String ValueIttLibraryID;
        String LabelIttLibraryMMM;
        String ValueIttLibraryMMM;
        String LabelIttLibraryName;
        String ValueIttLibraryName;
        String LabelIttLibraryCompiledDT;
        String ValueIttLibraryCompiledDT;
        String LabelIttLibraryNamespace;
        String ValueIttLibraryNamespace;
        */
    }

}
