namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableWindow : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableWindow();
    
        String LabelBuildTheme;
        String ValueBuildTheme;
        String LabelBuildUIScale;
        String ValueBuildUIScale;
        String LabelBuildAntiAliasing;
        String ValueBuildAntiAliasing;
        String LabelBuildFullScreen;
        String ValueBuildFullScreen;
        String LabelBuildResolution;
        String ValueBuildResolution;
        String LabelBuildRefreshRate;
        String ValueBuildRefreshRate;
        String LabelBuildFont;
        String ValueBuildFont;
        String LabelBuildFontSize;
        String ValueBuildFontSize;
        String LabelBuildFontWeight;
        String ValueBuildFontWeight;
    }

}
