namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableWindow : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableWindow();
    
        void SelectDefaultFromTables(String uid);

    }

}
