namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass TableRuntimeClass : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableRuntimeClass();
    
        String LabelRTCHVID;
        String ValueRTCHVID;
        String LabelRTCMMM;
        String ValueRTCMIL;
        String ValueRTCMAJ;
        String ValueRTCMIN;
        String LabelRTCMaxPath;
        String ValueRTCMaxPath;
        String LabelRTCNamespace;
        String ValueRTCNamespace;
        String LabelRTC;
        String ValueRTC;
        String LabelRTCCompiled;
        String ValueRTCCompiled;
        String LabelRTCDLL;
        String ValueRTCDLL;

    }

}
