namespace HV4DX
{
    [default_interface]
    runtimeclass TableParamLibrary : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableParamLibrary();
    
        void SelectDefaultFromTables(String uid);

    }

}
