namespace HV4DX
{
    [default_interface]
    runtimeclass TableLvl3Account : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableLvl3Account();

        void SelectDefaultFromTables(String uid);

    }

}
