namespace HV4DX
{
    [default_interface]
    runtimeclass TablePartition : Microsoft.UI.Xaml.Controls.UserControl
    {
        TablePartition();
    
        void SelectDefaultFromTables(String uid);

    }

}
