namespace HV4DX
{
    [default_interface]
    runtimeclass TableUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableUserControl();
        
        void SelectDefaultFromTables(String uid);

    }

}
