namespace HV4DX
{
    [default_interface]
    runtimeclass TableDrive : Microsoft.UI.Xaml.Controls.Page
    {
        TableDrive();

        String LabelPartitionHVID;
        String ValuePartitionHVID;
        String LabelPartitionName;
        String LabelPartitionType;
        String LabelPartitionCreatedDATETIME;
        String ValuePartitionCreatedDATETIME;
        String LabelPartitionSavedDATETIME;
        String ValuePartitionSavedDATETIME;
        String LabelPartitionOpenedDATETIME;
        String ValuePartitionOpenedDATETIME;
        String LabelReserved;
        String ValueReserved;
        String LabelAllocated;
        String ValueAllocated;
        String LabelClusterSize;
        String ValueClusterSize;
        String LabelPageSize;
        String ValuePageSize;
        String LabelAttSize;
        String ValueAttSize;
        String LabelIndexBufferSize;
        String ValueIndexBufferSize;
        
    }

}
