namespace HV4DX
{
    [default_interface]
    runtimeclass TableXamlToolBar : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableXamlToolBar();
        
        void SelectDefaultFromTables(String uid);

    }

}
