namespace HV4DX
{
    [default_interface]
    runtimeclass TableDrive : Microsoft.UI.Xaml.Controls.Page
    {
        TableDrive();
    
        String TableKey{ get; };
	
        void SelectDefaultFromTables(String uid);

    }

}
