namespace HV4DX
{
    [default_interface]
    runtimeclass TableKey : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableKey();
    
        String ValueKey;
	
        void SelectDefaultFromTables(String uid);

    }

}
