namespace HV4DX
{
    [default_interface]
    runtimeclass TableLvl2Account : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableLvl2Account();

        void SelectDefaultFromTables(String uid);

    }

}
