namespace HV4DX
{
    [default_interface]
    runtimeclass TableLvl1Account : Microsoft.UI.Xaml.Controls.Page
    {
        TableLvl1Account();
    
        void SelectDefaultFromTables(String uid);

    }

}
