namespace HV4DX
{
    [default_interface]
    runtimeclass TableNetworkAdapter : Microsoft.UI.Xaml.Controls.UserControl
    {
        TableNetworkAdapter();
    
        void SelectDefaultFromTables(String uid);

    }

}
