namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass UserMMM : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserMMM();
    
        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;
        
    }

}
