namespace HV4DX
{
    [bindable]
    runtimeclass UserFilterNew : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserFilterNew();
    
        String Label;
        UInt32 SelectedItem;
        Windows.Foundation.Collections.IObservableVector<String> ItemList;

    }

}
