namespace HV4DX
{
    [default_interface]
    runtimeclass UserFilterMMM : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserFilterMMM();

        String Label;
        String ValueMIL{ get; };
        String ValueMAJ{ get; };
        String ValueMIN{ get; };

    }

}
