namespace HV4DX
{
    [default_interface]
    runtimeclass UserDateTime : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserDateTime();

        String Label;
        String Value;
        String Placeholder;
        Boolean ReadOnly;
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

    }

}
