namespace HV4DX
{
    [bindable]
    [default_interface]
    runtimeclass UserBlock : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserBlock();

        String Label;
        String Value;

    }

}
