namespace HV4DX
{
    [bindable]
    runtimeclass UserFile : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserFile();

        String Label;
        String Value;

    }

}
