namespace HV4DX
{
    [bindable]
    runtimeclass UserFilterType : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserFilterType();

        String Label;

        String Value;

        Microsoft.UI.Xaml.Controls.TextBlock FilterType;
        Windows.Foundation.Collections.IObservableVector<Microsoft.UI.Xaml.Controls.TextBlock> FilterList;

    }

}
