namespace HV4DX
{
    [default_interface]
    runtimeclass UserDateTime : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserDateTime();
    
        String Label{ get; };
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;

    }

}
