namespace HV4DX
{
    [default_interface]
    runtimeclass UserFilterMMM : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserFilterMMM();

        String Label{ get; };
        String ValueMIL{ get; };
        String ValueMAJ{ get; };
        String ValueMIN{ get; };

    }

}
