namespace HV4DX
{
    [default_interface]
    runtimeclass UserGoToFile : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserGoToFile();

        String Label;
        String Value;
        String Placeholder;
        Boolean IsEditable;

    }

}
