namespace HV4DX
{
    [default_interface]
    runtimeclass UserTime : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserTime();

        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;

    }

}
