namespace HV4DX
{
    [default_interface]
    runtimeclass UserNumeric : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserNumeric();
    
        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;
        
    }

}
