namespace HV4DX
{
    [default_interface]
    runtimeclass UserHVID : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserHVID();

        String Label;
        String Value;

    }

}
