namespace HV4DX
{
    [bindable]
    runtimeclass UserPassword : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserPassword();

        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;
        
    }

}
