namespace HV4DX
{
    [bindable]
    runtimeclass UserEntry : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserEntry();

        String Label;

        String Value;
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        String Placeholder;
        
    }

}
