namespace HV4DX
{
    [bindable]
    runtimeclass UserEntry : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserEntry();
    
        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;

    }

}
