namespace HV4DX
{
    [bindable]
    runtimeclass UserEntry : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserEntry();
    
        String Label{ get; };
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;

    }

}
