namespace HV4DX
{
    [bindable]
    runtimeclass UserFilterType : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserFilterType();

        String Label;
        String Value;
        UInt32 FilterType;
        Windows.Foundation.Collections.IObservableVector<String> FilterList;

    }

}
