namespace HV4DX
{
    [default_interface]
    runtimeclass UserDate : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserDate();
    
        String Label;
        String Placeholder{ get; };
        String Value;

        Boolean ReadOnly;

    }

}
