namespace HV4DX
{
    [bindable]
    runtimeclass UserPassword : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserPassword();
    
        String Label;
        String Value;
        String Placeholder;
        Boolean ReadOnly;
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

    }

}
