namespace HV4DX
{
    [bindable]
    runtimeclass UserFilterItem : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserFilterItem();

        String Label;
        UInt32 SelectedItem;
        Windows.Foundation.Collections.IObservableVector<String> ItemList;
        Boolean IsEditable{ get; };

    }

}
