namespace Duality23
{
    [bindable]
    [default_interface]
    runtimeclass UserMSelectable : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserMSelectable(String e);

        String Selectable;

        Boolean Selected;

    }

}