namespace Duality23
{
    [bindable]
    [default_interface]
    runtimeclass UserCombo : 
            Microsoft.UI.Xaml.Controls.UserControl,
            Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserCombo();

        String Label;

        String Item{ get; };
        
        Windows.Foundation.Collections.IObservableVector<String> ItemList;

        Boolean Editable;

    }

}
