SET search_path=hv4d_schema_public;
DROP TABLE IF EXISTS HV4D_TABLE_PROFILE;
CREATE TABLE HV4D_TABLE_PROFILE(
PROFILE_HVID HV4D_TYPE_HVID PRIMARY KEY,
PROFILE_MMM HV4D_TYPE_MMM NOT NULL,
PROFILE_TAG HV4D_TYPE_MAXPATH NOT NULL,
	UNIQUE(PROFILE_TAG, PROFILE_MMM),
PROFILE_CREATED HV4D_TYPE_DATETIME NOT NULL,
PROFILE_UPDATED HV4D_TYPE_DATETIME NOT NULL,
PROFILE_CURRENT HV4D_TYPE_MAXPATH NOT NULL,
PROFILE_CONTACT_HVID HV4D_TYPE_HVID NOT NULL,
CONSTRAINT HV4D_FKEY_CONTACT
	FOREIGN KEY(PROFILE_CONTACT_HVID)
	REFERENCES HV4D_TABLE_CONTACT(CONTACT_HVID));