namespace HV4DABI
{
	[uuid(5BA9645C-F8C0-4A8B-86BF-6AB114E91E26)]
	[version(0x10000001)]
	interface IDebug : IInspectable
	{
		/*
		HV4D.HV4DRETURN HV4DNavigateCoreTriage(Object sender, INTERUPT e);

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageIndex;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageDUALITY;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageBoot;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageVolume;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageBatch;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageAttribute;

		event Windows.Foundation.TypedEventHandler<Object, INTERUPT> HV4DTriageFileTree;
		*/
	};

    [default_interface]
    runtimeclass HV4DDEBUG
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DDEBUG();


    }

}
