namespace HV4DABI
{
    [uuid(820C717E-92DE-4A41-88A4-079C4F707575)]
    [version(0x10000001)]
    interface IOStream : IInspectable
    {


    }

    [default_interface]
    runtimeclass HV4DOSTREAM
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DOSTREAM();


    }

}
