namespace HV4DABI
{
    [uuid(CDDAF7F9-F131-4938-AFB6-C4F97F21BACB)]
    [version(0x10000001)]
    interface IEvent : IInspectable
    {

    }

    [default_interface]
    runtimeclass HV4DEVENT
            : HV4DT.IHV4DTPROVIDER
    {
        HV4DEVENT();


    }

}
