SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_ACCELERATOR;
CREATE TABLE HV4D_TABLE_ACCELERATOR(
ACCELERATOR_HVID HV4D_TYPE_HVID PRIMARY KEY,
ACCELERATOR_HARDWARE_HVID HV4D_TYPE_HVID NOT NULL,
CONSTRAINT HV4D_FKEY_HARDWARE 
	FOREIGN KEY (ACCELERATOR_HARDWARE_HVID) 
	REFERENCES HV4D_TABLE_HARDWARE(HARDWARE_HVID));