SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_HARDWARE;
CREATE TABLE HV4D_TABLE_HARDWARE(
HARDWARE_MANUFACTURER HV4D_TYPE_MAXPATH NOT NULL,
HARDWARE_MODEL_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
HARDWARE_MODEL_TAG HV4D_TYPE_MAXPATH NOT NULL,
HARDWARE_HVID HV4D_TYPE_HVID PRIMARY KEY,
HARDWARE_ID HV4D_TYPE_ID NOT NULL,
HARDWARE_MAXPATH HV4D_TYPE_MAXPATH NOT NULL,
HARDWARE_BUILT HV4D_TYPE_DATETIME NOT NULL,
HARDWARE_INSTALLED HV4D_TYPE_DATETIME NOT NULL,
HARDWARE_UPDATED HV4D_TYPE_DATETIME NOT NULL,
HARDWARE_MAPPING_HVID HV4D_TYPE_HVID NOT NULL,
CONSTRAINT HV4D_FKEY_HARDWARE_MAPPING
	FOREIGN KEY(HARDWARE_MAPPING_HVID)
	REFERENCES HV4D_TABLE_HARDWARE_MAPPING(HARDWARE_MAPPING_HVID));