DROP TABLE IF EXISTS HV4D_TABLE_ACCELERATOR;
CREATE TABLE HV4D_TABLE_ACCELERATOR(
ACCELERATOR_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
ACCELERATOR_HARDWARE_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(ACCELERATOR_HARDWARE_HVID),
CONSTRAINT HV4D_FKEY_HARDWARE 
FOREIGN KEY (ACCELERATOR_HARDWARE_HVID) 
REFERENCES HV4D_TABLE_HARDWARE(HARDWARE_HVID));