DROP TABLE IF EXISTS HV4D_TABLE_DEVICE;
CREATE TABLE HV4D_TABLE_DEVICE(
DEVICE_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
DEVICE_TAG HV4D_TYPE_MAXPATH NOT NULL,
DEVICE_COMPORT HV4D_TYPE_MAXPATH NOT NULL,
PRIMARY KEY(DEVICE_HVID));