namespace HV4DSYSCALL
{
    [default_interface]
    runtimeclass HV4DKEYMAP
    {
		HV4DKEYMAP();
    
		HV4D.HV4DRETURN HV4DCharToNumeric(Char c, out UInt32 o);

		HV4D.HV4DRETURN HV4DCharFromNumeric(UInt32 e, out Char c);

		HV4D.HV4DRETURN HV4DCharIsHex(Char e);

		HV4D.HV4DRETURN HV4DCharIsNumeric(Char e);

		HV4D.HV4DRETURN HV4DCharIsAlphaNumeric(Char e);

		HV4D.HV4DRETURN HV4DCharIsSymbol(Char e);

    }

}
