namespace Duality137
{
    [default_interface]
    runtimeclass ProjectIndex : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ProjectIndex();

        String ValueProjectIndexHVID;
        String ValueProjectIndexMMM;
        String ValueProjectIndexTag;
        String ValueProjectIndexCreated;
        String ValueProjectIndexUpdated;
        String ValueProjectIndexDatabase;
        String ValueProjectIndexSchema;
        String ValueProjectIndexAccessLevel;
        String ValueProjectIndexAdministratorHVID;
        String ValueProjectIndexAdministratorTag;
        String[] ValueProjectIndexPermissions;

    }

}
