namespace Duality137
{
    [bindable]
    [default_interface]
    runtimeclass UserPassword : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserPassword();

        String Label;

        String Value;

    }

}
