namespace Duality137
{
    [bindable]
    [default_interface]
    runtimeclass UserFilterNew : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserFilterNew();
    
        String Label;

        String Value;

        event Windows.Foundation.EventHandler<String> FilterChanged;

    }

}
