namespace Duality137
{
    [bindable]
    [default_interface]
    runtimeclass UserVMDebug : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserVMDebug();

        String LabelHVID;

        String ValueHVID;

        String LabelType;

        String ValueType;

    }

}
