namespace Duality137
{
    [bindable]
    [default_interface]
    runtimeclass UserFile : Microsoft.UI.Xaml.Controls.UserControl
    {
        UserFile();

        String Label;

        String Value;

        String Placeholder;

    }

}
