SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_SOFT_PARTITION;
CREATE TABLE HV4D_TABLE_SOFT_PARTITION(
SOFT_PARTITION_HVID HV4D_TYPE_HVID PRIMARY KEY,
SOFT_PARTITION_NAME HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
SOFT_PARTITION_FORMAT HV4D_TYPE_MAXPATH NOT NULL,
SOFT_PARTITION_CREATED HV4D_TYPE_DATETIME NOT NULL,
SOFT_PARTITION_UPDATED HV4D_TYPE_DATETIME NOT NULL,
SOFT_PARTITION_OPENED HV4D_TYPE_DATETIME NOT NULL,
SOFT_PARTITION_HV4DVOL_OFF HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DVOL_SZ HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DSFT_OFF HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DSFT_SZ HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DMIR_OFF HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DMIR_SZ HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DATT_OFF HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DATT_SZ HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DBMP_OFF HV4D_TYPE_NUMERIC_U64 NOT NULL,
SOFT_PARTITION_HV4DBMP_SZ HV4D_TYPE_NUMERIC_U64 NOT NULL,
CONSTRAINT HV4D_ENUM_PARTITION_FORMAT check(
	SOFT_PARTITION_FORMAT in (
		'HV4D_PARTITION_LION', 
		'HV4D_PARTITION_ORCA')));