SET search_path=hv4d_schema_machine_001;
DROP TABLE IF EXISTS HV4D_TABLE_SERVICE;
CREATE TABLE HV4D_TABLE_SERVICE(
SERVICE_HVID HV4D_TYPE_HVID PRIMARY KEY,
SERVICE_MMM HV4D_TYPE_MMM NOT NULL,
SERVICE_TAG HV4D_TYPE_MAXPATH NOT NULL,
	UNIQUE(SERVICE_TAG, SERVICE_MMM),
SERVICE_COMPILED HV4D_TYPE_DATETIME NOT NULL,
SERVICE_INSTALLED HV4D_TYPE_DATETIME NOT NULL,
SERVICE_UPDATED HV4D_TYPE_DATETIME NOT NULL,
SERVICE_DLL_PATH HV4D_TYPE_MAXPATH NOT NULL,
SERVICE_DLL HV4D_TYPE_MAXPATH NOT NULL,
SERVICE_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
SERVICE_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL,
SERVICE_SUPPORTED_CONTRACT HV4D_TYPE_HVID[] NOT NULL,
SERVICE_ACCESS_LVL HV4D_TYPE_MAXPATH NOT NULL,
SERVICE_CONTACT_HVID HV4D_TYPE_HVID NOT NULL,
CONSTRAINT HV4D_FKEY_CONTACT
	FOREIGN KEY (SERVICE_CONTACT_HVID) 
	REFERENCES hv4d_schema_public.HV4D_TABLE_CONTACT(CONTACT_HVID));