DROP TABLE IF EXISTS HV4D_TABLE_XAML_FILE;
CREATE TABLE HV4D_TABLE_XAML_FILE(
XAML_FILE_SERVICE_HVID HV4D_TYPE_HVID NOT NULL,
XAML_FILE_SERVICE HV4D_TYPE_MAXPATH NOT NULL,
XAML_FILE_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
XAML_FILE_ID HV4D_TYPE_ID NOT NULL UNIQUE,
XAML_FILE_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
XAML_FILE_SUPPORTED_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
XAML_FILE_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
XAML_FILE_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
XAML_FILE_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
XAML_FILE_XAML_FILE_PATH HV4D_TYPE_MAXPATH NOT NULL,
XAML_FILE_XAML_FILE HV4D_TYPE_MAXPATH NOT NULL,
XAML_FILE_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(XAML_FILE_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (XAML_FILE_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));