DROP TABLE IF EXISTS HV4D_TABLE_PARAMETER;
CREATE TABLE HV4D_TABLE_PARAMETER(
PARAMETER_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
PARAMETER_ID HV4D_TYPE_ID NOT NULL UNIQUE,
PARAMETER_TAG HV4D_TYPE_MAXPATH NOT NULL,
PARAMETER_NAMESPACE HV4D_TYPE_MAXPATH NOT NULL,
PARAMETER_RUNTIME_CLASS HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
PARAMETER_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
PARAMETER_VALUE_HVID HV4D_TYPE_HVID NOT NULL,
PARAMETER_SUPPORTED_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
PARAMETER_DICTIONARY_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(PARAMETER_HVID),
CONSTRAINT HV4D_FKEY_DICTIONARY 
FOREIGN KEY (PARAMETER_DICTIONARY_HVID) 
REFERENCES HV4D_TABLE_DICTIONARY(DICTIONARY_HVID));