DROP TABLE IF EXISTS HV4D_TABLE_CONTRACT_MEMBER;
CREATE TABLE HV4D_TABLE_CONTRACT_MEMBER(
CONTRACT_MEMBER_HVID HV4D_TYPE_HVID NOT NULL UNIQUE,
CONTRACT_MEMBER_ID HV4D_TYPE_ID NOT NULL UNIQUE,
CONTRACT_MEMBER_TAG HV4D_TYPE_MAXPATH NOT NULL UNIQUE,
CONTRACT_MEMBER_TYPE HV4D_TYPE_MAXPATH NOT NULL,
CONTRACT_MEMBER_POSITION HV4D_TYPE_UINT NOT NULL,
CONTRACT_MEMBER_ARITY HV4D_TYPE_UINT NOT NULL,
CONTRACT_MEMBER_CONTRACT_HVID HV4D_TYPE_HVID NOT NULL,
PRIMARY KEY(CONTRACT_MEMBER_HVID),
CONSTRAINT HV4D_FKEY_CONTRACT 
FOREIGN KEY (CONTRACT_MEMBER_CONTRACT_HVID) 
REFERENCES HV4D_TABLE_CONTRACT(CONTRACT_HVID));